package ch.epfl.cs107.play.game.areagame;

import ch.epfl.cs107.play.game.areagame.actor.Interactable;
import ch.epfl.cs107.play.game.areagame.actor.Interactor;
import ch.epfl.cs107.play.math.DiscreteCoordinates;
import ch.epfl.cs107.play.window.Window;

import java.util.*;


public abstract class AutoGeneratedMazeBehavior extends AreaBehavior{

    /// Random generator for the maze
    protected final Random rand;

    /**
     * Default AreaBehavior Constructor
     * @param window (Window): graphic context, not null
     */
    public AutoGeneratedMazeBehavior(Window window, int width, int height, long seed){

        super(window, width<15 ? 15 : width, height<15 ? 15 : height); //Test the width and height of the AreaBehavior to be sure it is over 14X14

        rand = new Random(seed);
    }



}
