package ch.epfl.cs107.play.game.superpacman.area;

import ch.epfl.cs107.play.game.areagame.AreaGraph;
import ch.epfl.cs107.play.game.areagame.actor.Orientation;
import ch.epfl.cs107.play.game.rpg.actor.Door;
import ch.epfl.cs107.play.game.superpacman.actor.Gate;
import ch.epfl.cs107.play.game.superpacman.actor.Ghost;
import ch.epfl.cs107.play.game.superpacman.actor.SuperPacmanPlayer;
import ch.epfl.cs107.play.io.FileSystem;
import ch.epfl.cs107.play.math.DiscreteCoordinates;
import ch.epfl.cs107.play.signal.logic.Logic;
import ch.epfl.cs107.play.window.Window;

import java.util.ArrayList;
import java.util.Queue;

public class MazeLevel extends SuperPacmanArea{


    private SuperPacmanAutoGeneratedMazeBehavior behavior;
    private ArrayList<Ghost> areaGhostActors;
    private AreaGraph areaGraph;

    private int diamondCount;
    private int mazeNumber;

    private static DiscreteCoordinates PLAYER_SPAWN_POSITION;

    public MazeLevel(int a){
        mazeNumber = a;
    }


    @Override
    protected void createArea() {

        String destination = "superpacman/MazeLevel" + (mazeNumber+1);

        Door door = new Door(destination, new DiscreteCoordinates(1, getHeight()-2), Logic.TRUE, this, Orientation.UP, new DiscreteCoordinates(4,0), new DiscreteCoordinates(5,0));
        registerActor(door);

        Gate[] gates = new Gate[2];
        gates[0] = new Gate(this, Orientation.RIGHT, new DiscreteCoordinates(5,1), Logic.TRUE /*this*/);
        gates[1] = new Gate(this, Orientation.LEFT, new DiscreteCoordinates(4,1), Logic.TRUE /*this*/);

        for (Gate gate : gates) {
            registerActor(gate);
        }
    }

    @Override
    public boolean begin(Window window, FileSystem fileSystem){
        behavior = new SuperPacmanAutoGeneratedMazeBehavior(window, 40, 40);
        if (super.begin(window, fileSystem, behavior)) {
            // Set the behavior map
            PLAYER_SPAWN_POSITION = behavior.getSpawnPoint();
            return true;
        }
        return false;
    }

    @Override
    public String getTitle() {
        return "superpacman/MazeLevel"+mazeNumber;
    }

    public ArrayList<Ghost> getAreaGhostActors(){
        return areaGhostActors;
    }

    public Queue<Orientation> shortestPath(DiscreteCoordinates origine, DiscreteCoordinates arrivee){
        return(behavior.shortestPath(origine, arrivee));
    }

    public void scareCheck(SuperPacmanPlayer player){
        behavior.scareCheck(player);
    }

    public AreaGraph getAreaGraph(){return areaGraph;}

    public void addDiamond(){ diamondCount++; }

    public void removeDiamond(){ diamondCount--; }


    @Override
    public DiscreteCoordinates getSpawnPoint() {
        return behavior.getSpawnPoint();
    }

    @Override
    public boolean isOn() { return !isOff();}

    @Override
    public boolean isOff() { return diamondCount>0;}

    @Override
    public float getIntensity() {
        if(isOn()){
            return 1.f;
        } else {
            return 0.f;
        }
    }

    @Override
    public void update(float deltaTime) {
        super.update(deltaTime);
    }

    public int getMazeNum(){ return mazeNumber; }

}
