package ch.epfl.cs107.play.game.superpacman.area;

import ch.epfl.cs107.play.game.areagame.Area;
import ch.epfl.cs107.play.game.areagame.AreaGraph;
import ch.epfl.cs107.play.game.areagame.actor.Orientation;
import ch.epfl.cs107.play.game.superpacman.actor.Ghost;
import ch.epfl.cs107.play.game.superpacman.actor.SuperPacmanPlayer;
import ch.epfl.cs107.play.game.superpacman.userInterface.End.EndDisplay;
import ch.epfl.cs107.play.game.superpacman.userInterface.Pause.PauseScreen;
import ch.epfl.cs107.play.game.superpacman.userInterface.SuperPacmanAreaGUIEntity;
import ch.epfl.cs107.play.game.superpacman.userInterface.SuperPacmanGUIBehavior;
import ch.epfl.cs107.play.io.FileSystem;
import ch.epfl.cs107.play.math.DiscreteCoordinates;
import ch.epfl.cs107.play.signal.logic.Logic;
import ch.epfl.cs107.play.window.Keyboard;
import ch.epfl.cs107.play.window.Window;

import java.util.ArrayList;
import java.util.Queue;

public abstract class SuperPacmanArea extends Area implements Logic {

    protected abstract void createArea();
    private SuperPacmanBehavior behavior;
    private ArrayList<Ghost> areaGhostActors;
    private AreaGraph areaGraph;
    public static float cameraScaleFactor = 15.f;

    private int diamondCount;

    private boolean pause, gameEnd, win, backToMenu;
    private int finalScore;

    private Window window;

    private SuperPacmanAreaGUIEntity displayPause;
    private SuperPacmanAreaGUIEntity displayEnd;


    public boolean begin(Window window, FileSystem fileSystem) {
        if (super.begin(window, fileSystem)) {
            // Set the behavior map
            behavior = new SuperPacmanBehavior(window, getTitle());
            setBehavior(behavior);
            behavior.registerActors(this);
            pause = false;
            gameEnd = false;
            win = false;
            backToMenu = false;
            finalScore = 0;
            this.window = window;

            createArea();
            displayPause = new SuperPacmanAreaGUIEntity(this, new PauseScreen(this));
            registerActor(displayPause);
            return true;
        }
        return false;
    }

    public boolean begin(Window window, FileSystem fileSystem, SuperPacmanAutoGeneratedMazeBehavior behavior) {
        if (super.begin(window, fileSystem)) {
            // Set the behavior map
            this.behavior = behavior;
            setBehavior(behavior);
            behavior.registerActors(this);
            pause = false;

            createArea();
            displayPause = new SuperPacmanAreaGUIEntity(this, new PauseScreen(this));
            registerActor(displayPause);
            return true;
        }
        return false;
    }

    public boolean begin(Window window, FileSystem fileSystem, SuperPacmanGUIBehavior behavior) {
        if (super.begin(window, fileSystem)) {
            // Set the behavior map
            this.behavior = behavior;
            setBehavior(behavior);
            //behavior.registerActors(this);
            pause = false;

            createArea();
            displayPause = new SuperPacmanAreaGUIEntity(this, new PauseScreen(this));
            registerActor(displayPause);
            return true;
        }
        return false;
    }

    public void deactivateNode(DiscreteCoordinates coordinates, Logic logic){
        behavior.deactivateNode(coordinates, logic);
    }

    public ArrayList<Ghost> getAreaGhostActors(){
        return areaGhostActors;
    }

    public Queue<Orientation> shortestPath(DiscreteCoordinates origine, DiscreteCoordinates arrivee){
        return(behavior.shortestPath(origine, arrivee));
    }

    public void scareCheck(SuperPacmanPlayer player){
        behavior.scareCheck(player);
    }

    public void BackToRefugeAndForget(){
        behavior.BackToRefugeAndForget();
    }

    public AreaGraph getAreaGraph(){return areaGraph;}

    public boolean isCellWalkable(DiscreteCoordinates coordinates, String SIDE){
        if(behavior.isCellWalkableBehavior(coordinates, SIDE)){
            return true;
        }
        else{
            return false;
        }
    }

    public void addDiamond(){ diamondCount++; }

    public void removeDiamond(){ diamondCount--; }

    public final float getCameraScaleFactor(){return cameraScaleFactor;}

    public abstract DiscreteCoordinates getSpawnPoint();

    @Override
    public boolean isOn() { return !isOff();}

    @Override
    public boolean isOff() { return diamondCount>0;}

    @Override
    public float getIntensity() {
        if(isOn()){
            return 1.f;
        } else {
            return 0.f;
        }
    }

    @Override
    public void update(float deltaTime) {
        super.update(deltaTime);

        Keyboard keyboard= this.getKeyboard();
        if(keyboard.get(Keyboard.P).isPressed()){
            suspend();
        }

        /*if(keyboard.get(Keyboard.ENTER).isPressed() && pause && gameEnd){
            backToMenu = true;
        }*/
    }

    @Override
    public void suspend(){
        super.suspend();
        pause = !pause;
        System.out.println("pause : "+pause);

        if(gameEnd){
            displayEnd = new SuperPacmanAreaGUIEntity(this, new EndDisplay(this, win, finalScore));
            registerActor(displayEnd);
        }
    }

    public boolean isPaused(){ return pause; }

    public void finish(boolean win, int finalScore){
        gameEnd = true;
        this.win = win;
        this.finalScore = finalScore;
        suspend();
    }

    public boolean isGameEnd(){ return gameEnd; }

    public boolean getBackToMenu(){ return backToMenu; }

}
